version: 2
updates:
- package-ecosystem: "npm"
  directory: "/ukelonn.web.frontend/src/main/frontend/"
  schedule:
    interval: monthly
  target-branch: "using-react"
  groups:
    npm-all:
      applies-to: version-updates
      patterns:
        - "*"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  target-branch: "using-react"
  ignore:
    # ignore Maven APIs/SPIs
    - dependency-name: org.apache.maven:*
